-- Migration 002 — Seed IOC country codes
-- INSERT OR IGNORE is safe to re-run (idempotent).

INSERT OR IGNORE INTO nocs (code, country) VALUES ('AFG', 'Afghanistan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ALB', 'Albania');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ALG', 'Algeria');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('AND', 'Andorra');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ANG', 'Angola');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ARG', 'Argentina');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ARM', 'Armenia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('AUS', 'Australia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('AUT', 'Austria');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('AZE', 'Azerbaijan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BAH', 'Bahamas');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BEL', 'Belgium');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BEN', 'Benin');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BLR', 'Belarus');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BOL', 'Bolivia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BIH', 'Bosnia and Herzegovina');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BOT', 'Botswana');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BRA', 'Brazil');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BUL', 'Bulgaria');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('BUR', 'Burkina Faso');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CAM', 'Cambodia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CMR', 'Cameroon');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CAN', 'Canada');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CHI', 'Chile');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CHN', 'China');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('COL', 'Colombia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CGO', 'Congo');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CRC', 'Costa Rica');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CIV', 'Côte d''Ivoire');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CRO', 'Croatia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CUB', 'Cuba');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CYP', 'Cyprus');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('CZE', 'Czech Republic');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('DEN', 'Denmark');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('DOM', 'Dominican Republic');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ECU', 'Ecuador');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('EGY', 'Egypt');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ESA', 'El Salvador');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('EST', 'Estonia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ETH', 'Ethiopia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('FIN', 'Finland');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('FRA', 'France');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('GAB', 'Gabon');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('GEO', 'Georgia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('GER', 'Germany');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('GHA', 'Ghana');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('GBR', 'Great Britain');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('GRE', 'Greece');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('GUA', 'Guatemala');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('HKG', 'Hong Kong');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('HUN', 'Hungary');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('IND', 'India');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('INA', 'Indonesia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('IRI', 'Iran');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('IRL', 'Ireland');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ISR', 'Israel');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ITA', 'Italy');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('JAM', 'Jamaica');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('JPN', 'Japan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('JOR', 'Jordan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('KAZ', 'Kazakhstan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('KEN', 'Kenya');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('PRK', 'Korea (North)');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('KOR', 'Korea (South)');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('KUW', 'Kuwait');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('KGZ', 'Kyrgyzstan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('LAT', 'Latvia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('LBA', 'Libya');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('LIE', 'Liechtenstein');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('LTU', 'Lithuania');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('LUX', 'Luxembourg');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('MAS', 'Malaysia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('MLT', 'Malta');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('MAR', 'Morocco');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('MEX', 'Mexico');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('MDA', 'Moldova');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('MON', 'Monaco');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('MGL', 'Mongolia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('MNE', 'Montenegro');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('NED', 'Netherlands');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('NZL', 'New Zealand');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('NCA', 'Nicaragua');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('NGR', 'Nigeria');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('NOR', 'Norway');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('PAK', 'Pakistan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('PAN', 'Panama');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('PAR', 'Paraguay');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('PER', 'Peru');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('PHI', 'Philippines');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('POL', 'Poland');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('POR', 'Portugal');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('PUR', 'Puerto Rico');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('QAT', 'Qatar');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ROM', 'Romania');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('RUS', 'Russia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SEN', 'Senegal');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SRB', 'Serbia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SGP', 'Singapore');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SVK', 'Slovakia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SLO', 'Slovenia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('RSA', 'South Africa');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ESP', 'Spain');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SRI', 'Sri Lanka');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SWE', 'Sweden');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SUI', 'Switzerland');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('SYR', 'Syria');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('TPE', 'Chinese Taipei');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('TJK', 'Tajikistan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('THA', 'Thailand');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('TUN', 'Tunisia');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('TUR', 'Turkey');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('TKM', 'Turkmenistan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('UGA', 'Uganda');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('UKR', 'Ukraine');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('UAE', 'United Arab Emirates');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('USA', 'United States');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('URU', 'Uruguay');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('UZB', 'Uzbekistan');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('VEN', 'Venezuela');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('VIE', 'Vietnam');
INSERT OR IGNORE INTO nocs (code, country) VALUES ('ZIM', 'Zimbabwe');
