-- Migration: Create Competition and CompetitionFencer tables
CREATE TABLE IF NOT EXISTS Competitions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  date DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CompetitionFencers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  competitionId INTEGER NOT NULL,
  fencerId INTEGER NOT NULL,
  seed INTEGER,
  status TEXT DEFAULT 'registered',
  state TEXT,
  final_rank INTEGER,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (competitionId) REFERENCES Competitions(id) ON DELETE CASCADE,
  FOREIGN KEY (fencerId) REFERENCES Fencers(id) ON DELETE CASCADE
);
