#!/usr/bin/env bash
# sync-mosquitto-scoresheet-acl.sh — regenerate Mosquitto's *entire* acl.conf (there's
# only one) from Atlas's own DB: Tier B (docs/security-provisioning-discussion.md §4.5,
# username/password) credentials AND Tier A (docs/level2.md §30.5, TLS client
# certificate) issued devices both live in this one file, since Mosquitto has only one
# acl_file — two independently-regenerating scripts would just clobber each other.
# scripts/sync-mosquitto-tier-a.sh is the companion script for the *other* half of Tier
# A (pushing ca.crl and the listener-8883 require_certificate/crlfile config), which
# doesn't touch acl.conf at all and so has no clobber risk with this one.
#
# Tier B: one username/password per device, all non-revoked pool entries valid at the
# broker regardless of whether they've been assigned to a device yet (assignment is
# pure Atlas-DB bookkeeping — see services/pairing.js's assignCredential — the broker
# doesn't distinguish "free" from "assigned", only "revoked" from "not revoked").
#
# Tier A: certificates authenticate via `use_identity_as_username true` on listener
# 8883 (see scripts/sync-mosquitto-tier-a.sh) — the cert's CN becomes the ACL username,
# same per-user stanza mechanism as Tier B, just no passwd_file entry needed.
#
# Also carries the one global write grant an as-yet-uncertified Tier A device needs to
# even start provisioning: openpiste/_provision/request (docs/level2.md §30.5) — must
# stay anonymous-writable, since a brand-new device has no credential yet by definition.
#
# Read access, and apparatus/remote/var publishing, stay exactly as open to anonymous
# connections as before — this only gates scoresheet/* (Tier B) and grants Tier A
# devices their own scoped read+write. Full per-piste scoping is still a real, separate
# follow-up (see docs/implementation-notes/mosquitto-security.md's "what this note
# doesn't cover").
#
# software is the one exception, as of 2026-07-15: it is NOT in the anonymous
# backward-compat block below. Only Atlas's own CMS ever publishes as software, and it
# now authenticates via its own Tier A client certificate (CN software-cms — see
# scripts/provision-cms-client-cert.sh) instead of connecting anonymously. Leaving
# software/# anonymously writable after that would have meant any other anonymous
# client on the network could spoof software/* messages the apparatus is
# spec-required to trust unconditionally (e.g. software/clock's running:false
# invariant) — closed once the CMS's own certificate was confirmed working over mTLS.
#
# Usage:
#   ./scripts/sync-mosquitto-scoresheet-acl.sh
#
# Safe to re-run — fully regenerates the passwd/ACL files from Atlas's DB each time
# (not an incremental patch), so it's the same command whether you just topped up the
# Tier B pool, revoked a Tier B device, or issued/revoked a Tier A certificate.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PASSWD_FILE="/etc/mosquitto/passwd"
ACL_FILE="/etc/mosquitto/acl.conf"
CONF_SNIPPET="/etc/mosquitto/conf.d/scoresheet-acl.conf"

echo "Reading active Tier B credentials from Atlas's DB..."
CREDENTIALS=$(node -e "
  const db = require('$DIR/db');
  const rows = db.prepare('SELECT username, password FROM mqtt_credentials WHERE revoked_at IS NULL').all();
  rows.forEach(r => console.log(r.username + ':' + r.password));
")

COUNT=$(echo "$CREDENTIALS" | grep -c . || true)
echo "$COUNT active Tier B credential(s) to push."

echo "Reading active Tier A certificates from Atlas's DB..."
TIER_A_DEVICES=$(node -e "
  const db = require('$DIR/db');
  const rows = db.prepare('SELECT role, device_id FROM tier_a_certificates WHERE revoked_at IS NULL').all();
  rows.forEach(r => console.log(r.role + ':' + r.role + '-' + r.device_id));
")
TIER_A_COUNT=$(echo "$TIER_A_DEVICES" | grep -c . || true)
echo "$TIER_A_COUNT active Tier A certificate(s) to push."

echo "Rebuilding Mosquitto password file (needs sudo)..."
TMP_PASSWD=$(mktemp)
FIRST=1
while IFS=: read -r username password; do
  [ -z "$username" ] && continue
  if [ "$FIRST" = 1 ]; then
    mosquitto_passwd -b -c "$TMP_PASSWD" "$username" "$password"
    FIRST=0
  else
    mosquitto_passwd -b "$TMP_PASSWD" "$username" "$password"
  fi
done <<< "$CREDENTIALS"
# No credentials yet — mosquitto_passwd needs at least a touch to produce a valid,
# empty (deny-all-by-username) file rather than leaving none at all.
[ "$FIRST" = 1 ] && touch "$TMP_PASSWD"

sudo cp "$TMP_PASSWD" "$PASSWD_FILE"
rm -f "$TMP_PASSWD"
sudo chown root:mosquitto "$PASSWD_FILE"
sudo chmod 640 "$PASSWD_FILE"

echo "Rebuilding ACL file..."
{
  echo "# Generated by scripts/sync-mosquitto-scoresheet-acl.sh — see"
  echo "# docs/security-provisioning-discussion.md §4.5 and"
  echo "# docs/implementation-notes/mosquitto-security.md."
  echo ""
  # CONFIRMED EMPIRICALLY (2026-07-14, re-verified 2026-07-15 against Mosquitto
  # 2.0.18): a bare "topic ..." line outside any "user" block ONLY reaches
  # anonymous connections — once a client authenticates (Tier B
  # username/password, or Tier A via use_identity_as_username), it gets *only*
  # what's inside its own "user <name>" stanza. This bit us three separate
  # times (read access, the _provision/response delivery, and a real device
  # being permanently unable to re-provision once its DB record was gone) before
  # this was understood as a pattern rather than three unrelated bugs.
  #
  # "pattern ..." lines are different: CONFIRMED (2026-07-15, disposable broker)
  # to apply to every client — anonymous AND authenticated — with zero per-user
  # repetition needed, even for a user with no stanza in this file at all. Used
  # below for every grant that's genuinely meant to be universal (read
  # everything; the provisioning channel). Role-scoped writes
  # (openpiste/+/{role}/#) deliberately stay as per-user "topic" lines below —
  # that scoping is real security boundary, not incidental, and must NOT become
  # universal via "pattern".
  echo "pattern read #"
  echo ""
  echo "# The provisioning channel MUST reach every client, anonymous or"
  echo "# authenticated — a brand-new device is anonymous (docs/level2.md §30.5),"
  echo "# an already-provisioned device re-requesting/renewing is authenticated,"
  echo "# and Atlas's own OPP2 client (which publishes the response) also connects"
  echo "# anonymously (lib/opp2Transport.js sets no username)."
  echo "pattern write openpiste/_provision/request"
  echo "pattern write openpiste/_provision/response/+"
  echo ""
  echo "# apparatus/remote/var keep publishing exactly as before — this is the"
  echo "# anonymous backward-compat fallback (Tier A provisioning for these roles"
  echo "# is optional, not required); deliberately NOT \"pattern\", since an"
  echo "# authenticated-but-wrong-role identity must not inherit this."
  echo "topic write openpiste/+/apparatus/#"
  echo "topic write openpiste/+/remote/#"
  echo "topic write openpiste/+/var/#"
  echo ""
  echo "# x_ST37_AI / x_ST37_SettingsManager (esp32scoringdeviceMqtt vendor"
  echo "# extension, docs/level2.md §5's \"new {publisher} values\" escape hatch --"
  echo "# see that repo's ST37_AIHandler.cpp / ST37_SettingsManagerHandler.cpp)."
  echo "# Anonymous by deliberate choice (2026-08-16), same tier as"
  echo "# apparatus/remote/var above -- unlike software, these aren't spoofing"
  echo "# spec-critical CMS state the apparatus trusts unconditionally; the"
  echo "# apparatus-side gate is its own \"Experimental\" runtime flag (off by"
  echo "# default, never persisted), not broker auth."
  echo "topic write openpiste/+/x_ST37_AI/#"
  echo "topic write openpiste/+/x_ST37_SettingsManager/#"
  echo ""
  echo "# software is deliberately absent above — see the header comment. Atlas's own"
  echo "# CMS certificate (role=software, device_id=cms) picks up its write grant"
  echo "# below via the same per-user Tier A loop as any other certificate."
  echo ""
  echo "# ── Tier B (username/password) — role-scoped write only; read/provisioning"
  echo "# already come from the \"pattern\" lines above ──"
  while IFS=: read -r username password; do
    [ -z "$username" ] && continue
    echo "user $username"
    echo "topic write openpiste/+/scoresheet/#"
    echo ""
  done <<< "$CREDENTIALS"

  echo "# ── Tier A (TLS client certificate, CN = username via use_identity_as_username)"
  echo "# — role-scoped write only, same reasoning as Tier B above ──"
  while IFS=: read -r role cn; do
    [ -z "$role" ] && continue
    echo "user $cn"
    echo "topic write openpiste/+/${role}/#"
    echo ""
  done <<< "$TIER_A_DEVICES"
} > /tmp/atlas-scoresheet-acl.conf
sudo cp /tmp/atlas-scoresheet-acl.conf "$ACL_FILE"
rm -f /tmp/atlas-scoresheet-acl.conf
sudo chown root:mosquitto "$ACL_FILE"
sudo chmod 640 "$ACL_FILE"

echo "Ensuring password_file/acl_file are enabled..."
sudo tee "$CONF_SNIPPET" > /dev/null <<EOF
password_file $PASSWD_FILE
acl_file $ACL_FILE
EOF

echo "Reloading mosquitto (SIGHUP — does not drop existing connections)..."
sudo kill -HUP "$(pidof mosquitto)" 2>/dev/null || sudo systemctl reload mosquitto

echo ""
echo "Done. $COUNT Tier B credential(s) and $TIER_A_COUNT Tier A certificate(s) now"
echo "valid at the broker."
echo ""
echo "Note: acl.conf grants Tier A devices their topic access once identified by"
echo "certificate — it does NOT itself make listener 8883 require a certificate, map"
echo "its CN to a username, or check revocation. Run"
echo "./scripts/sync-mosquitto-tier-a.sh separately for that (one-time listener"
echo "config: use_identity_as_username, require_certificate, crlfile — plus pushing"
echo "the current CRL, needed again after every revoke)."
