#!/usr/bin/env bash
# sync-mosquitto-scoresheet-acl.sh — push Atlas's current mqtt_credentials pool
# (docs/security-provisioning-discussion.md §4.5) out to Mosquitto: one
# username/password per device, all non-revoked pool entries valid at the broker
# regardless of whether they've been assigned to a device yet (assignment is pure
# Atlas-DB bookkeeping — see services/pairing.js's assignCredential — the broker
# doesn't distinguish "free" from "assigned", only "revoked" from "not revoked").
#
# Replaces the old setup-mosquitto-auth.sh (single shared credential). Read access,
# and apparatus/software/remote/var publishing, stay exactly as open as before — this
# only gates the scoresheet/* topics. Full per-piste scoping is still a real, separate
# follow-up (see docs/implementation-notes/mosquitto-security.md's "what this note
# doesn't cover").
#
# Usage:
#   ./scripts/sync-mosquitto-scoresheet-acl.sh
#
# Safe to re-run — fully regenerates the passwd/ACL files from Atlas's DB each time
# (not an incremental patch), so it's the same command whether you just topped up the
# pool (scripts/top-up-credential-pool.js) or just revoked a device in pairing.html.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PASSWD_FILE="/etc/mosquitto/passwd"
ACL_FILE="/etc/mosquitto/acl.conf"
CONF_SNIPPET="/etc/mosquitto/conf.d/scoresheet-acl.conf"

echo "Reading active credentials from Atlas's DB..."
CREDENTIALS=$(node -e "
  const db = require('$DIR/db');
  const rows = db.prepare('SELECT username, password FROM mqtt_credentials WHERE revoked_at IS NULL').all();
  rows.forEach(r => console.log(r.username + ':' + r.password));
")

COUNT=$(echo "$CREDENTIALS" | grep -c . || true)
echo "$COUNT active credential(s) to push."

echo "Rebuilding Mosquitto password file (needs sudo)..."
TMP_PASSWD=$(mktemp)
FIRST=1
while IFS=: read -r username password; do
  [ -z "$username" ] && continue
  if [ "$FIRST" = 1 ]; then
    mosquitto_passwd -b -c "$TMP_PASSWD" "$username" "$password"
    FIRST=0
  else
    mosquitto_passwd -b "$TMP_PASSWD" "$username" "$password"
  fi
done <<< "$CREDENTIALS"
# No credentials yet — mosquitto_passwd needs at least a touch to produce a valid,
# empty (deny-all-by-username) file rather than leaving none at all.
[ "$FIRST" = 1 ] && touch "$TMP_PASSWD"

sudo cp "$TMP_PASSWD" "$PASSWD_FILE"
rm -f "$TMP_PASSWD"
sudo chown root:mosquitto "$PASSWD_FILE"
sudo chmod 640 "$PASSWD_FILE"

echo "Rebuilding ACL file..."
{
  echo "# Generated by scripts/sync-mosquitto-scoresheet-acl.sh — see"
  echo "# docs/security-provisioning-discussion.md §4.5 and"
  echo "# docs/implementation-notes/mosquitto-security.md."
  echo ""
  echo "# Applies to every client, authenticated or anonymous — read stays universal,"
  echo "# and apparatus/software/remote/var keep publishing exactly as before (Tier A"
  echo "# provisioning for those roles is not yet built)."
  echo "topic read #"
  echo "topic write openpiste/+/apparatus/#"
  echo "topic write openpiste/+/software/#"
  echo "topic write openpiste/+/remote/#"
  echo "topic write openpiste/+/var/#"
  echo ""
  # NOTE: the "topic read #" above only actually reaches anonymous connections on
  # this Mosquitto (confirmed empirically against 2.0.18, 2026-07-14) — once a
  # client authenticates with a username, it is granted *only* whatever appears
  # inside its own "user <name>" block below, so read has to be repeated per-user
  # or a paired device's subscriptions silently receive nothing (SUBACK still
  # succeeds, which makes this easy to miss without testing actual delivery).
  while IFS=: read -r username password; do
    [ -z "$username" ] && continue
    echo "user $username"
    echo "topic read #"
    echo "topic write openpiste/+/scoresheet/#"
    echo ""
  done <<< "$CREDENTIALS"
} > /tmp/atlas-scoresheet-acl.conf
sudo cp /tmp/atlas-scoresheet-acl.conf "$ACL_FILE"
rm -f /tmp/atlas-scoresheet-acl.conf
sudo chown root:mosquitto "$ACL_FILE"
sudo chmod 640 "$ACL_FILE"

echo "Ensuring password_file/acl_file are enabled..."
sudo tee "$CONF_SNIPPET" > /dev/null <<EOF
password_file $PASSWD_FILE
acl_file $ACL_FILE
EOF

echo "Reloading mosquitto (SIGHUP — does not drop existing connections)..."
sudo kill -HUP "$(pidof mosquitto)" 2>/dev/null || sudo systemctl reload mosquitto

echo ""
echo "Done. $COUNT credential(s) now valid at the broker."
